In [6]:
lag = 12
config = {"batch": 256, "epochs": 600}
file1 = 'train.csv'
file2 = 'test.csv'
X_train, y_train, _, _, _ = process_data(file1, file2, lag)

C:\Users\19863\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [29]:
"""
Processing the data
"""
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler


def process_data(train, test, lags):
    """Process data
    Reshape and split train\test data.

    # Arguments
        train: String, name of .csv train file.
        test: String, name of .csv test file.
        lags: integer, time lag.
    # Returns
        X_train: ndarray.
        y_train: ndarray.
        X_test: ndarray.
        y_test: ndarray.
        scaler: StandardScaler.
    """
    attr = 'Lane 1 Flow (Veh/5 Minutes)'
    df1 = pd.read_csv(train, encoding='utf-8').fillna(0)
    df2 = pd.read_csv(test, encoding='utf-8').fillna(0)

    # scaler = StandardScaler().fit(df1[attr].values)
    scaler = MinMaxScaler(feature_range=(0, 1)).fit(df1[attr].values.reshape(-1, 1))
#     .reshape(1, -1)[0]
    flow1 = scaler.transform(df1[attr].values.reshape(-1, 1))
    flow2 = scaler.transform(df2[attr].values.reshape(-1, 1))

    train, test = [], []
    for i in range(lags, len(flow1)):
        train.append(flow1[i - lags: i + 1])
    for i in range(lags, len(flow2)):
        test.append(flow2[i - lags: i + 1])

    train = np.array(train)
    test = np.array(test)
#     np.random.shuffle(train)

    X_train = train[:, :-1]
    y_train = train[:, -1]
    X_test = test[:, :-1]
    y_test = test[:, -1]

    return X_train, y_train, X_test, y_test, scaler


In [30]:
lag = 12
config = {"batch": 256, "epochs": 600}
file1 = 'train.csv'
file2 = 'test.csv'
X_train, y_train, _, _, _ = process_data(file1, file2, lag)

C:\Users\19863\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [28]:
for i in range(5):
    print(X_train[i])

[ 0.06091371  0.06598985  0.05583756  0.06598985  0.05076142  0.05076142
  0.06598985  0.05583756  0.05076142  0.03045685  0.03553299  0.04060914]
[ 0.06598985  0.05583756  0.06598985  0.05076142  0.05076142  0.06598985
  0.05583756  0.05076142  0.03045685  0.03553299  0.04060914  0.04060914]
[ 0.05583756  0.06598985  0.05076142  0.05076142  0.06598985  0.05583756
  0.05076142  0.03045685  0.03553299  0.04060914  0.04060914  0.06091371]
[ 0.06598985  0.05076142  0.05076142  0.06598985  0.05583756  0.05076142
  0.03045685  0.03553299  0.04060914  0.04060914  0.06091371  0.03553299]
[ 0.05076142  0.05076142  0.06598985  0.05583756  0.05076142  0.03045685
  0.03553299  0.04060914  0.04060914  0.06091371  0.03553299  0.02538071]


In [20]:
for i in range(5):
    print(X_train[i])

[ 0.41624365  0.40101523  0.40101523  0.40101523  0.44162437  0.40609137
  0.40101523  0.3857868   0.32994924  0.42639594  0.30456853  0.31979695]
[ 0.03045685  0.03553299  0.01522843  0.01015228  0.01522843  0.00507614
  0.02030457  0.03045685  0.02030457  0.03553299  0.03553299  0.03553299]
[ 0.05583756  0.05583756  0.06598985  0.05583756  0.03553299  0.04568528
  0.05583756  0.03553299  0.03045685  0.04568528  0.03553299  0.02538071]
[ 0.54822335  0.52284264  0.52284264  0.58375635  0.54822335  0.50253807
  0.54314721  0.52284264  0.43654822  0.48730964  0.56852792  0.54822335]
[ 0.03045685  0.03045685  0.04060914  0.01522843  0.05076142  0.08629442
  0.08629442  0.05076142  0.05583756  0.07106599  0.08121827  0.16751269]


In [31]:
for i in range(5):
    print(X_train[i])

[[ 0.06091371]
 [ 0.06598985]
 [ 0.05583756]
 [ 0.06598985]
 [ 0.05076142]
 [ 0.05076142]
 [ 0.06598985]
 [ 0.05583756]
 [ 0.05076142]
 [ 0.03045685]
 [ 0.03553299]
 [ 0.04060914]]
[[ 0.06598985]
 [ 0.05583756]
 [ 0.06598985]
 [ 0.05076142]
 [ 0.05076142]
 [ 0.06598985]
 [ 0.05583756]
 [ 0.05076142]
 [ 0.03045685]
 [ 0.03553299]
 [ 0.04060914]
 [ 0.04060914]]
[[ 0.05583756]
 [ 0.06598985]
 [ 0.05076142]
 [ 0.05076142]
 [ 0.06598985]
 [ 0.05583756]
 [ 0.05076142]
 [ 0.03045685]
 [ 0.03553299]
 [ 0.04060914]
 [ 0.04060914]
 [ 0.06091371]]
[[ 0.06598985]
 [ 0.05076142]
 [ 0.05076142]
 [ 0.06598985]
 [ 0.05583756]
 [ 0.05076142]
 [ 0.03045685]
 [ 0.03553299]
 [ 0.04060914]
 [ 0.04060914]
 [ 0.06091371]
 [ 0.03553299]]
[[ 0.05076142]
 [ 0.05076142]
 [ 0.06598985]
 [ 0.05583756]
 [ 0.05076142]
 [ 0.03045685]
 [ 0.03553299]
 [ 0.04060914]
 [ 0.04060914]
 [ 0.06091371]
 [ 0.03553299]
 [ 0.02538071]]


In [ ]:
"""
Traffic Flow Prediction with Neural Networks(SAEs、LSTM、GRU).
"""
import math
import warnings
import numpy as np
import pandas as pd
from data.data import process_data
from keras.models import load_model
from keras.utils.vis_utils import plot_model
import sklearn.metrics as metrics
import matplotlib as mpl
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")



def plot_results(y_true, y_preds, names):
    """Plot
    Plot the true data and predicted data.

    # Arguments
        y_true: List/ndarray, ture data.
        y_pred: List/ndarray, predicted data.
        names: List, Method names.
    """
    d = '2016-3-4 00:00'
    x = pd.date_range(d, periods=288, freq='5min')

    fig = plt.figure()
    ax = fig.add_subplot(111)

    ax.plot(x, y_true, label='True Data')
    for name, y_pred in zip(names, y_preds):
        ax.plot(x, y_pred, label=name)

    plt.legend()
    plt.grid(True)
    plt.xlabel('Time of Day')
    plt.ylabel('Flow')

    date_format = mpl.dates.DateFormatter("%H:%M")
    ax.xaxis.set_major_formatter(date_format)
    fig.autofmt_xdate()

    plt.show()


def main():
    lstm = load_model('model/lstm.h5')
    gru = load_model('model/gru.h5')
    saes = load_model('model/saes.h5')
    models = [lstm, gru, saes]
    names = ['LSTM', 'GRU', 'SAEs']

    lag = 12
    file1 = 'data/train.csv'
    file2 = 'data/test.csv'
    _, _, X_test, y_test, scaler = process_data(file1, file2, lag)
    y_test = scaler.inverse_transform(y_test.reshape(-1, 1)).reshape(1, -1)[0]

    y_preds = []
    for name, model in zip(names, models):
        if name == 'SAEs':
            X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1]))
        else:
            X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
        file = 'images/' + name + '.png'
        plot_model(model, to_file=file, show_shapes=True)
        predicted = model.predict(X_test)
        predicted = scaler.inverse_transform(predicted.reshape(-1, 1)).reshape(1, -1)[0]
        y_preds.append(predicted[:288])
        print(name)
        eva_regress(y_test, predicted)

    plot_results(y_test[: 288], y_preds, names)
